apiVersion: v1
kind: Service
metadata:
  name: drone-service
  labels:
    run: drone-service
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8000
      nodePort: 31088
  selector:
    app: drone
