apiVersion: v1
kind: Pod
metadata:
  name: droneio-master
  labels:
    app: drone
spec:
  containers:
  - name: dron
    image: drone/drone:0.7
    env:
      - name: DRONE_OPEN
        value: "true"
      - name: DRONE_STASH
        value: "true"
      - name: DRONE_STASH_URL
        value: "https://stash.hybris.com"
      - name: DRONE_STASH_GIT_USERNAME
        value: "XXX"
      - name: DRONE_STASH_GIT_PASSWORD
        value: "XXX"
      - name: DRONE_SECRET
        value: "myDroneSecret"
      - name: DRONE_HOST
        value: "marios-master.k8s.rot.hybris.com"
    ports:
    - containerPort: 8000
    volumeMounts:
      - name: drone-storage
        mountPath: /var/lib/drone
  volumes:
    - name: drone-storage
      hostPath:
        path: /tmp

---

apiVersion: v1
kind: Service
metadata:
  name: drone-service
  labels:
    run: drone-service
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8000
    nodePort: 31088
  selector:
    app: drone
---
apiVersion: v1
kind: Pod
metadata:
  name: droneio-worker
  labels:
    app: droneioworker
spec:
  containers:
  - name: droneworker
    image: drone/drone:0.7
    args:
      - "agent"
    env:
      - name: DRONE_SERVER
        value: "ws://marios-master.k8s.rot.hybris.com:31088/ws/broker"
      - name: DRONE_SECRET
        value: "myDroneSecret"
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
